### ISSUE TITLE
Load the block's transactions into the Cairo vm using a hint and log the hashes.

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/keth#10]

**Comment by tcoratger** [comment]
@ClementWalter I'm not sure about the best approach to use here. I think what @greged93 had in mind here is the following approach:
- We have our ExEx currently in the code that notifies us of each new block.
- For each new block, we re-execute for the moment the transactions with the REVM.
- The goal of this issue was to take these transactions for each block, make a JSON with their hashes, enter this JSON in the Cairo VM as program input and simply do a print.
- From what I see, in Python it's easy, you just have to use the approach described here which does exactly what we want: https://docs.cairo-lang.org/how_cairo_works/program_input_and_output.html#program-input
- But in the Cairo VM in Rust that we use there is nothing equivalent from what I see. Moonsong Labs uses the following approach to introduce a Starknet OS input https://github.com/Moonsong-Labs/snos/blob/6376bb61f08d25dfbe68d670be542d5d3dcee029/src/hints/mod.rs#L190 but I'm not sure if it's really equivalent and probably not adapted to what we want to do I would say no? It seemed native in the Python VM but not in the Rust VM. What do you think?

**Comment by greged93** [comment]
I don't think there is another way, you can't load a file like in the python vm so you need to read one using a custom hint. Maybe (but I don't know if possible) you could pass a channel to the hint? I have no clue if there is a way to do that with the current definition of hints

**Comment by tcoratger** [comment]
But then maybe there is something I don't understand due to my lack of knowledge about Cairo hints but for me, the hint in question is specific to load a `StarknetOsInput` which is a very particular structure defined here https://github.com/Moonsong-Labs/snos/blob/6376bb61f08d25dfbe68d670be542d5d3dcee029/src/io/input.rs#L18 and which allows to load an OS with specific fields like here https://raw.githubusercontent.com/Moonsong-Labs/snos/6376bb61f08d25dfbe68d670be542d5d3dcee029/build/os_latest.json

But not a simple JSON which would be for example

```
[
"hash1": 0x1,
"hash2": 0x2
]
```
no?

**Comment by greged93** [comment]
Hint in the Cairo vm in rust are just used to match on. You could write a hint like "HELLO", match on it and execute arbitrary rust code in it. So it doesn't really matter what you write in the hint, what is import is what the prover does
